### ISSUE TITLE
Display order number on marker

### ISSUE THREAD

**Issue by moonlight200** [machbarschaft/machbarschaft-android#6]
The marker of an order on the map currently only consists of the flag symbol. Display the order number on the flag similar to the flags in the order list to quickly identify which marker belongs to which order.

**Comment by Basler182** [comment]
It maybe would be also good to have different markers for the different tasks, which helps the user to determine quickly what he has to do (Shopping, Medicine, Car, etc?). Maybe also in a different colors to determine how urgent each task is.

**Comment by alexanderhodes** [comment]
the idea with those different colors sounds great. We could define it in our app. But it should be consistent to our ios app

**Comment by moonlight200** [comment]
The flags are already colored depending on the urgency of the order. Didn't we define that in the first version of the wireframe?

**Comment by alexanderhodes** [comment]
yes, the flags are already colored according to the urgency. Is there still anything to do? Otherwise this issue should be closed

**Comment by alexanderhodes** [comment]
red = urgent, yellow = today, green = tomorrow and gray = anytime

**Comment by moonlight200** [comment]
The coloring is done, but as the original issue stated, the numbers are not displayed on all flags. They are displayed on the flags in the order list, but not on the flags in the map.

**Comment by Basler182** [comment]
Our current problem is, that the user cant see on the map what kind of order it is. He has to press on every order and check the details. It would be good to instantly see, what kind of order it is.
For this problem, I have two ideas which could solve this.

#1 
We simply implement the Display Order Number on the Marker, and add a Listener, so that the List below the map gets automatically adapted to the current position. This makes it more user friendly, if you swipe around the map, cause the user has it easy to find the corresponding list item. 

#2 
We could add different icons for specific orders. For example, a pill could show that its a 'medicine'-task. The user will instantly see what kind of order it is and he doesn't have to search for it in the list view noir does he have to press on it.

The best way would probably to implement both. 

What are your thoughts about it?

**Comment by moonlight200** [comment]
1. Adding a type based icon will make it very easy to identify the general type (and urgency via the color) of a task. 2. The number links the marker in the map to an exact entry in the list. The list can provide even more details (like e.g. is a car recommended for the order).
Thus implementing both would probably be the best.

About the listener you mentioned in 1.:
Do you mean, that the list is constantly being updated based on the markers that are visible on the map? So that when the user zooms out, they will see a longer list and when they move the view to an entirely different location, the list will be updated accordingly. Should all of this happen independent of the users actual location? As we currently have a limitation to which orders are displayed based on a certain distance to the user. If an order is too far away, the user cannot see the order.

**Comment by Basler182** [comment]
finally works
